language: android
android:
  components:
    - build-tools-19.0.3

notifications:
  email: false

before_install:

  # for gradle output style
  - export TERM=dumb

  # environment info
  - ./gradlew -v
  - uname -a


before_script:
  - chmod +x ci/wait_for_emulator.sh
  - ci/wait_for_emulator.sh
  # Unlock screen
  - adb shell input keyevent 82 &
